# sudo: false
language: generic

addons:
  apt:
    packages:
 #     - mlton
      - mlton-compiler
      - smlnj
      - libcml-smlnj
      - libcmlutil-smlnj
      - libsmlnj-smlnj

cache:
 directories:
 - $HOME/.mlton
      
before_install:
#- git clone https://github.com/MLton/mlton MLton/mlton
#- cd MLton/mlton
#- make
#- sudo make PREFIX=$HOME/.mlton install
- export PATH=$HOME/.mlton/bin:$PATH
 
script:
- mlton
- uname -a
- mlton -output n2o.exe n2o.mlb
- ml-build n2o.cm Main.main n2o.nj
